general:
  debug: false
  language: "en"

alerts:
  enabled: true
  staff-alerts: true
  console-alerts: true
  webhook-url: ""
  alert-format: "&8[&bGenAC&8] &f{player} &8failed &f{check} &8(&f{vl}&8) &8- &f{details}"

checks:
  invmove:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: false
        threshold: 10
        duration: 1800

  wallhit:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 3
      ban:
        enabled: true
        threshold: 6
        duration: 1800

  wallbuild:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 3
      ban:
        enabled: true
        threshold: 6
        duration: 1800

  reach:
    enabled: true
    experimental: false
    cancel: true
    punishment:
      kick:
        enabled: false
        threshold: 5
      ban:
        enabled: false
        threshold: 10
        duration: 3600

  killaurarotationa:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 6
      ban:
        enabled: false
        threshold: 12
        duration: 3600

  killaurarotationb:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

  killaurarotationc:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

  killaurarotationd:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

  wallinteract:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

  sprintb:
    enabled: true
    max_violations: 3
    cancel: false
    min_sprint_interval: 100
    max_sprint_rate: 8
    false_positive_protection: true

  packettimer:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

  negativetimer:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600