general:
  debug: false
  language: "en"

alerts:
  staff-alerts: true
  console-alerts: true
  webhook-url: ""

checks:
  baritone:
    enabled: true
    experimental: true
    punishment:
      kick:
        enabled: false
        threshold: 5
      ban:
        enabled: false
        threshold: 10
        duration: 1800
  invmove:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: false
        threshold: 10
        duration: 1800

  wallhit:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 3
      ban:
        enabled: true
        threshold: 6
        duration: 1800

  reach:
    enabled: true
    experimental: false
    cancel: true
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: false
        threshold: 10
        duration: 3600

  killaurarotationa:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 6
      ban:
        enabled: false
        threshold: 12
        duration: 3600

  killaurarotationb:
    enabled: true
    experimental: false
    punishment:
      kick:
        enabled: true
        threshold: 5
      ban:
        enabled: true
        threshold: 10
        duration: 3600

punishments:
  kick-message: "§cYou have been kicked for suspicious activity: {reason} ({violations} violations)"
  ban-command: "tempban {player} {duration} Suspicious activity: {reason} ({violations} violations)"

functions:
